/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOANNMODPDF
#define ROOANNMODPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "DMRate.hh"

 
class RooAnnModPdf : public RooAbsPdf {
public:
  RooAnnModPdf() {} ; 
  RooAnnModPdf(const char *name, const char *title,
	      RooAbsReal& _energy,
	      RooAbsReal& _time,
	      RooAbsReal& _sSI,
	      RooAbsReal& _mW);
  RooAnnModPdf(const RooAnnModPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAnnModPdf(*this,newname); }
  virtual ~RooAnnModPdf();

  int initialize(const char * fileRate);

  //virtual Double_t	expectedEvents(const RooArgSet& nset) const;

protected:

  RooRealProxy energy ;
  RooRealProxy  time ;
  RooRealProxy  sSI ;
  RooRealProxy  mW ;

  DMRate * fDMRate;

  Double_t evaluate() const ;


private:

  ClassDef(RooAnnModPdf,1) // Your description goes here...
};
 
#endif
