/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooAnnModPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

#include "DMPhysConstants.hh"
#include "DMRate.hh"

ClassImp(RooAnnModPdf) 

RooAnnModPdf::RooAnnModPdf(const char *name, const char *title, 
                        RooAbsReal& _energy,
                        RooAbsReal& _time,
                        RooAbsReal& _sSI,
                        RooAbsReal& _mW) :
   RooAbsPdf(name,title), 
   energy("energy","energy",this,_energy),
    time(" time"," time",this,_time),
    sSI(" sSI"," sSI",this,_sSI),
    mW(" mW"," mW",this,_mW),
    fDMRate(0)
{ 
} 


 RooAnnModPdf::RooAnnModPdf(const RooAnnModPdf& other, const char* name) :  
   RooAbsPdf(other,name), energy("energy",this,other.energy),
   time(" time",this,other.time), sSI(" sSI",this,other.sSI), mW(" mW",this,other.mW)
{ 
  fDMRate = new DMRate(*other.fDMRate);
} 

 RooAnnModPdf::~RooAnnModPdf()
{
  if (fDMRate) delete fDMRate;
}


int RooAnnModPdf::initialize(const char * fileRate)
{
  if (fDMRate) delete fDMRate;

  fDMRate = new DMRate();
  fDMRate->Initialize((char * )fileRate);

  fDMRate->SetMW(mW);
  fDMRate->SetSigSI(sSI);
}

 Double_t RooAnnModPdf::evaluate() const 
 { 

   DMRate theRate (*fDMRate);

   theRate.SetMW(mW);
   theRate.SetSigSI(sSI);

   double S0, Sm, Phi;

   int err = theRate.Rate(energy, &S0, &Sm, &Phi);

   double Phi_d = Phi*365; // Phi is in years
   double retval = S0 + Sm * cos(DAYTORAD*(time - Phi_d));

   return retval;
 } 

//Double_t RooAnnModPdf::expectedEvents(const RooArgSet& nset) const
// { 
// } 



